[deps]
BifurcationForecasting = "b4655097-ae25-5163-bf61-d3c9a0adde9a"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"

[sources]
BifurcationForecasting = {path = "/home/runner/work/BifurcationForecasting.jl/BifurcationForecasting.jl"}

[compat]
Documenter = "1"
